version: '3'
services:
  envoy:
    image: envoyproxy/envoy-dev
    working_dir: /envoy
    command:
    - -c
    - envoy.yaml
    - --component-log-level
    - wasm:debug
    - -l
    - warning
    ports:
    - "18000:18000"
    volumes:
    - .:/envoy
    - wasm-volume:/wasm
  wasm:
    build: .
    command:
      - cp
      - plugin.wasm
      - /wasm
    volumes:
    - wasm-volume:/wasm
volumes:
  wasm-volume:
